Repository KiraCore/interx, pull requests merged in 2022-03, with the labels that each got.

#26 GithubActions v0.0.0.4 -> latest
  .github/workflows/main.yml
Labels: kira-automation

#28 GithubActions v0.0.0.4 -> latest
  .github/workflows/main.yml
Labels: kira-automation

#29 GithubActions v0.0.0.4 -> latest
  .github/workflows/main.yml
Labels: kira-automation

#30 GithubActions v0.0.0.4 -> latest
  .github/workflows/main.yml
Labels: kira-automation, automerge

#32 GithubActions v0.0.0.5 -> latest
  RELEASE.md
Labels: kira-automation, automerge

#34 GithubActions v0.0.0.5 -> latest
  .github/workflows/main.yml
Labels: kira-automation, automerge

#36 GithubActions v0.0.0.5 -> latest
  .github/workflows/main.yml
Labels: kira-automation, automerge

#38 GithubActions v0.0.0.5 -> latest
  .github/workflows/main.yml
Labels: kira-automation, automerge

#40 GithubActions v0.4.1.1 -> latest
  .github/workflows/main.yml
  config/constants.go
  gateway/cosmos/auth.go
  gateway/cosmos/bank.go
  gateway/interx/validators.go
  gateway/kira/gov.go
  gateway/kira/identity_registrar.go
  gateway/kira/permission.go
  gateway/kira/proposal.go
  gateway/kira/role.go
  gateway/kira/tokens.go
  gateway/kira/upgrade.go
  go.mod
  go.sum
  main.go
  scripts/proto-gen.sh
Labels: kira-automation, automerge

#42 GithubActions v0.4.1.1 -> latest
  .github/workflows/main.yml
  .github/workflows/master.yml
Labels: kira-automation, automerge

#45 GithubActions v0.4.1.1 -> latest
  .github/workflows/main.yml
  .github/workflows/master.yml
Labels: kira-automation, automerge

#52 v0.4.1-rc.5 -> latest
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  .github/workflows/spam.yml
  DEVME.md
  RELEASE.md
  go.mod
  scripts/proto-gen.sh
  scripts/publish.sh
Labels: kira-automation, automerge

#55 v0.4.1-rc.5 -> latest
  .github/workflows/master.yml
Labels: kira-automation, automerge

#54 v0.4.1-rc.5 -> master
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  .github/workflows/spam.yml
  DEVME.md
  RELEASE.md
  go.mod
  scripts/proto-gen.sh
  scripts/publish.sh
Labels: kira-automation

#57 Update query endpoints
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/master.yml
  .github/workflows/spam.yml
  DEVME.md
  RELEASE.md
  config/constants.go
  config/init.go
  functions/interx.go
  gateway/kira/main.go
  gateway/kira/spending.go
  gateway/kira/ubi.go
  gateway/main.go
  go.mod
  postman/Kira.postman_collection.json
  scripts/proto-gen.sh
  scripts/publish.sh
Labels: invalid

#58 v0.4.1.2 -> latest
  config/constants.go
  config/init.go
  functions/interx.go
  gateway/kira/main.go
  gateway/kira/spending.go
  gateway/kira/ubi.go
  gateway/main.go
  postman/Kira.postman_collection.json
Labels: kira-automation, automerge

#59 feature/ci-cd-v1 -> v0.4.2-rc.1
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/spam.yml
  RELEASE.md
  config/constants.go
  config/init.go
  functions/interx.go
  gateway/kira/main.go
  gateway/kira/spending.go
  gateway/kira/ubi.go
  gateway/main.go
  go.mod
  go.sum
  postman/Kira.postman_collection.json
  scripts/publish.sh
  scripts/version.sh
Labels: kira-automation

#61 v0.4.2-rc.1 -> latest
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/spam.yml
  RELEASE.md
  config/constants.go
  go.mod
  go.sum
  scripts/publish.sh
  scripts/version.sh
Labels: kira-automation, automerge

#60 v0.4.2-rc.1 -> master
  .github/workflows/branch.yml
  .github/workflows/main.yml
  .github/workflows/spam.yml
  RELEASE.md
  config/constants.go
  config/init.go
  functions/interx.go
  gateway/kira/main.go
  gateway/kira/spending.go
  gateway/kira/ubi.go
  gateway/main.go
  go.mod
  go.sum
  postman/Kira.postman_collection.json
  scripts/publish.sh
  scripts/version.sh
Labels: kira-automation
