Repository KiraCore/interx, pull requests merged in 2024-03, with the labels that each got.

#223 release/v0.4.46 -> master
  config/constants.go
  tasks/node_discover.go
  types/nodes.go
Labels: kira-automation

#225 feature/cook_hook -> release/v0.4.47
  .github/workflows/merge_hook.yml
  Makefile
  RELEASE.md
  config/constants.go
  scripts/sbuild.sh
Labels: kira-automation

#227 release/v0.4.47 -> latest
  .github/workflows/merge_hook.yml
  Makefile
  RELEASE.md
  config/constants.go
  scripts/sbuild.sh
Labels: kira-automation, automerge

#226 release/v0.4.47 -> master
  .github/workflows/merge_hook.yml
  Makefile
  RELEASE.md
  config/constants.go
  scripts/sbuild.sh
Labels: kira-automation

#228 pub_p2p_list PeersNumber fix
  tasks/node_discover.go
Labels: invalid
